services:

  geoserver:
    image: docker.osgeo.org/geoserver:3.0.0
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      # Override default admin credentials
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      # Do not clutter Geoserver with demonstration data
      - SKIP_DEMO_DATA=true
      # Installing OGC API Features
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ogcapi-features
    volumes:
      # Optional: Persist GeoServer data directory to host
      - ./geoserver_data:/opt/geoserver_data
    restart: unless-stopped
