services:

  postgres:
    image: kartoza/postgis:13.0
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=geoserver
      - POSTGRES_PASSWORD=geoserver
      - POSTGRES_DB=geoserver
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./workshop-data:/tmp/workshop-data
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      # Override default admin credentials
      - GEOSERVER_ADMIN_PASSWORD=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      # Do not clutter Geoserver with demonstration data
      - SKIP_DEMO_DATA=true
      # Installing OGC API Features
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ogcapi-features
    volumes:
      # Optional: Persist GeoServer data directory to host
      - ./geoserver_data:/opt/geoserver_data
    depends_on:
      # Setup networking between the two containers
      - postgres
    restart: unless-stopped
