services:
  geoserver:
    image: kartoza/geoserver:2.28.2
    container_name: geoserver
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: hemmelig
      GEOSERVER_DATA_DIR: /opt/geoserver_data
    volumes:
      - ./data/geoserver:/opt/geoserver_data
    ports:
      - "8080:8080"
    restart: unless-stopped
